#!/bin/bash

backup_disk_mountpoint='/mnt/backup'

if ! findmnt "${backup_disk_mountpoint}"; then
    printf 'Nothing seems to be mounted at %s\n' "${backup_disk_mountpoint}"
    exit 1
fi

shopt -u dotglob

dirs=(
    "${HOME}"/*
    "${HOME}/.android"
    "${HOME}/.dosbox"
    "${HOME}/.mozilla"
)

rsync -a -v --sparse --delete-after "${dirs[@]}" "${backup_disk_mountpoint}/raghu/"
