#!/bin/bash

# Author: Raghu Rao <raghu.v.rao@gmail.com>

string1=" Hello! "
string2=".,;:0ODB8S5Il1|rnm"
d="$(tput sgr0 2>/dev/null)"
b="$(tput bold 2>/dev/null)"

do_it()
{
    if [[ "${1}" =~ [0-9]+ ]]; then c="$(tput setab ${1} 2>/dev/null)"; else c=""; fi
    echo -n -e "${c}${string1}${d} ${b}${c}${string1}${d} "
    if [[ "${1}" =~ [0-9]+ ]]; then c="$(tput setaf ${1} 2>/dev/null)"; else c=""; fi
    echo -e "${c}${string2}${d} ${b}${c}${string2}${d} ${1}"
}

echo -e "${d}"
do_it
#echo -e "  ${string1}${d}${b}${c}${string1}${d} ${c}${string2}${d} ${b}${c}${string2}${d}"
for i in {0..15}; do
    do_it ${i}
done
echo -e "${d}"
