#!/bin/bash

# Author: Raghu Rao <raghu.v.rao@gmail.com>

s="The quick brown fox"
d="$(tput sgr0 2>/dev/null)"
bo="$(tput bold 2>/dev/null)"

printf '%s' "${d}"
for i in {0..15}; do
    fg="$(tput setaf "${i}" 2>/dev/null)"
    bg="$(tput setab "${i}" 2>/dev/null)"
    printf '%s%s%s %s%s%s%s %s%s%s %s%s%s%s\n' \
        "${bg}" "${s}" "${d}" \
        "${bg}" "${bo}" "${s}" "${d}" \
        "${fg}" "${s}" "${d}" \
        "${fg}" "${bo}" "${s}" "${d}"
done
