#!/bin/bash

# Author: Raghu Rao <raghu.v.rao@gmail.com>

set -e

ac="$(tput colors 2>/dev/null)"
if [[ -z "${ac}" || ${ac} -le 0 ]]; then
    printf 'Cannot determine number of available colors.\n'
    exit 1
fi

start_color=0
end_color=${ac}

dc="${1}"
if [[ -n "${dc}" ]]; then
    if [[ ! "${dc}" =~ ^\+?[0-9]+$ || ${dc} -ge ${ac} || ${dc} -lt 0 ]]; then
        printf 'Argument, if provided, must be an integer N where 0<=N<%d\n' ${ac}
        exit 1
    fi
    start_color=${dc}
    end_color=$((dc+1))
fi

text="LOREM IPSUM"
d="$(tput sgr0 2>/dev/null)"

for (( i = ${start_color}; i < ${end_color}; i++ )); do
    fg="$(tput setaf ${i} 2>/dev/null)"
    bg="$(tput setab ${i} 2>/dev/null)"
    printf '\n%s%40d%s %s%s%s\n' "${bg}" "${i}" "${d}" "${fg}" "${text}" "${d}"
done
printf '\n'
