#!/bin/bash

# Author: Raghu Rao <raghu.v.rao@gmail.com>

bg="${1}"
if [[ -z "${bg}" || ${bg} -lt 0 || ${bg} -gt 15 ]]; then
    exit 1
fi

bg="$(tput setab "${bg}" 2>/dev/null)"
s1="THE QUICK BROWN FOX"
s2="JUMPS OVER THE LAZY DOG."
d="$(tput sgr0 2>/dev/null)"
bo="$(tput bold 2>/dev/null)"
for i in {0..15}; do
    fgs[${i}]="$(tput setaf ${i} 2>/dev/null)"
done

printf '%s' "${d}"
for y in "${fgs[@]}"; do
    printf '%s' "${bg}"
    printf '%s%s %s%s%s\n' "${y}" "${s1}" "${bo}" "${s2}" "${d}"
done
