#!/bin/bash

# Author: Raghu Rao <raghu.v.rao@gmail.com>

nc=${1}
if [[ -z "${nc}" ]]; then
    nc=16
fi
if [[ ( ${nc} -ne 8 ) && ( ${nc} -ne 16 ) ]]; then
    printf '%s\n' "Argument must be nil, 8, or 16" >&2
    exit 1
fi

declare -a fgs bgs
# Unlike in many other shells, arrays in bash are zero-based.
for (( i = 0 ; i < ${nc} ; i++ )); do
    fgs[${i}]="$(tput setaf ${i} 2>/dev/null)"
    bgs[${i}]="$(tput setab ${i} 2>/dev/null)"
done

d="$(tput sgr0 2>/dev/null)"

printf '%s' "${d}"

for bo in '' "$(tput bold 2>/dev/null)"; do
    i=0
    for p in "${fgs[@]}"; do
        printf '%2d ' ${i}
        for q in "${bgs[@]}"; do
            printf '%s%s%s xy %s' "${bo}" "${p}" "${q}" "${d}"
        done
        i=$((i + 1))
        printf '\n'
    done
    printf '\n'
done
