#!/bin/sh

for color1 in 1 2 3 4 5 6 7; do
    for color2 in 0 1 2 3 4 5 6 7 8; do
        tput setaf ${color1}
        tput setab ${color2}
        echo -n "wGy"
        tput bold
        echo -n " wGy"
        tput sgr0
        echo -n " "
    done
    echo
done
