#!/bin/sh

# This script is not meant to be sourced; it is meant to be run as a command.
# So, exporting variables in this script will not affect the parent shell.

if [ -z "${MANWIDTH}" ]; then
    # Using COLUMNS is unreliable because it may not be present if the shell is
    # non-interactive; 'tput cols' seems to be more reliable.
    c="`tput cols 2>/dev/null`"
    if [ $? -eq 0 -a $c -gt 80 ]; then
        export MANWIDTH=80
    fi
fi

exec /usr/bin/man "${@}"
