#!/usr/bin/env python3


# Author: Raghu Rao <raghu.v.rao@gmail.com>

# TODO: this script is similar in functionality to t.  See if t and this
# script can be unified.


import argparse
import datetime
import pytz
import sys

from datetime import datetime
from pytz import utc, timezone, UnknownTimeZoneError


def main():
    default_timezone = "Etc/UTC"

    parser = argparse.ArgumentParser(
        description="converts a given time and a timezone into other timezones.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument(
        "moment",
        type=str,
        help="the time to convert; see the input format option for the default format",
    )
    parser.add_argument(
        "-z",
        "--timezones",
        default="Etc/UTC,US/Pacific,US/Eastern,Asia/Kolkata",
        required=False,
        help="the timezones to which to convert the specified moment",
    )
    parser.add_argument(
        "-t",
        "--in-timezone",
        default=default_timezone,
        required=False,
        help="the timezone in which the moment is",
    )
    parser.add_argument(
        "-i",
        "--input-format",
        default="%Y-%m-%d-%H-%M-%S",
        required=False,
        help="input format (strftime)",
    )
    parser.add_argument(
        "-o",
        "--output-format",
        default="%Y-%m-%d %H:%M:%S %z %Z",
        required=False,
        help="output format (strftime)",
    )
    args = parser.parse_args()

    ret = 0
    in_format = args.input_format
    out_format = args.output_format

    try:
        input_timezone = timezone(args.in_timezone)
    except UnknownTimeZoneError as err:
        print(f"timezone: {err}", file=sys.stderr)
        ret = 2
        return ret

    try:
        moment = datetime.strptime(args.moment, in_format)
    except (KeyError, ValueError) as err:
        print(f"strptime: {err}", file=sys.stderr)
        ret = 2
        return ret

    moment = input_timezone.localize(moment)
    # Time delta between The UNIX Epoch and now.
    d = moment.astimezone(utc) - datetime(1970, 1, 1, 0, 0, 0, tzinfo=utc)
    print(f"{int(d.total_seconds())} UNIX")  # Ignore microseconds.

    # Work out which timezones we will be using.
    tzs = []
    unknown_tzs = []
    for tz in args.timezones.split(","):
        try:
            tzs.append(timezone(tz.strip()))
        except UnknownTimeZoneError:
            unknown_tzs.append(tz)
    if any(unknown_tzs):
        print(f"unknown timezones: {unknown_tzs}")
        ret = 1

    if not any(tzs):
        tzs = [timezone("Etc/UTC")]

    for tz in tzs:
        try:
            m = moment.astimezone(tz)
        except OverflowError as err:
            print(f"(ERROR: {err}) {tz}")
            ret = 1
            continue
        s = m.strftime(out_format)
        print(f"{s} {tz}")

    return ret


if __name__ == "__main__":
    sys.exit(main())
