#!/usr/bin/env python

# Author: Raghu Rao <raghu.v.rao@gmail.com>

import sys
import urllib

if len(sys.argv) > 1:
    print urllib.unquote(sys.argv[1])
else:
    print urllib.unquote(sys.stdin.read())
